services:
  postgres:
    image: postgres:latest
    container_name: plateful_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: plateful
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - plateful_network

  redis:
    image: redis:latest
    container_name: plateful_redis
    ports:
      - "6379:6379"
    networks:
      - plateful_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:  # ✅ הוספת שם השירות
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: plateful_backend
    depends_on:
      postgres:
        condition: service_healthy
    env_file:  # ✅ העברת `env_file` למיקום הנכון
      - ./backend/.env
    environment:
      DATABASE_URL: "postgresql://postgres:password123@postgres:5432/plateful"
    ports:
      - "8000:8000"
    volumes:
      - ./backend/static:/app/static  # ✅ תיקון גישה לקבצים סטטיים
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - plateful_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: plateful_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    networks:
      - plateful_network

networks:
  plateful_network:
    driver: bridge
