services:
  postgres:
    image: postgres:latest
    container_name: plateful_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: plateful
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - plateful_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plateful_backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:password123@postgres:5432/plateful"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static  # ✅ תיקון גישה לקבצים סטטיים
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8000"]  # ✅ תיקון Healthcheck
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - plateful_network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: plateful_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    networks:
      - plateful_network

networks:
  plateful_network:
    driver: bridge
